# -*- coding: utf-8 -*-
"""Question1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/152L92XbA8967szaYKAFdU_WsXCO9Gowt
"""

keywords = {"numbers":{
                        "zero": 0,
                        "one" : 1,
                        "two": 2,
                        "three": 3,
                        "four": 4,
                        "five": 5,
                        "six": 6,
                        "seven": 7,
                        "eight": 8,
                        "nine": 9,
                        "ten": 10,
                        "twenty": 20,
                        "thirty": 30,
                        "forty": 40,
                        "fifty": 50,
                        "sixty": 60,
                        "seventy": 70,
                        "eighty": 80,
                        "ninety": 90,
                        "hundred": 100
                        },
            "Tuples": {
                         "single":1,
                         "double":2,
                         "triple":3,
                         "quadruple":4,
                         "quintuple":5,
                         "sextuple":6,
                         "septuple":7,
                         "octuple":8,
                         "nonuple":9,
                         "decuple":10
                      },
            "General": {
                          "c.m": "CM",
                          "p.m": "PM",
                          "a.m": "AM"
                       },
            "price":{
                "dollars": "$",
            }
            }
print(keywords['numbers'])

text = input()

text=text.lower()
unwanted = ['?',',','!','@','<','>']
for i in unwanted:
  text=text.replace(i,'')

words=[x for x in text.split(' ')]
print(words)
a=[]
for k in range(len(words)):
  c=0
  for i,j in keywords.items():
    if(words[k] in j.keys()):
      if(i=='Tuples'):
        for l in range(j[words[k]]):
          a.append(words[k+1])
        c=2
      break
  if(c!=2):
    print(a)
    a.append(words[k])
print(text)
print(a)